// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3588.subsystems;



import org.usfirst.frc3588.RobotMap;
import org.usfirst.frc3588.commands.DriveRobotCommand;

import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveMotors extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController backLeft = RobotMap.driveMotorsBackLeft;
    SpeedController frontLeft = RobotMap.driveMotorsFrontLeft;
    SpeedController frontRight = RobotMap.driveMotorsFrontRight;
    SpeedController backRight = RobotMap.driveMotorsBackRight;
    RobotDrive robotDrive = RobotMap.driveMotorsRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new DriveRobotCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
        
    }
    
    public DriveMotors()	{
//    	robotDrive.setInvertedMotor(MotorType.kFrontRight, true);
//    	robotDrive.setInvertedMotor(MotorType.kRearRight, true);
//    	robotDrive.setInvertedMotor(MotorType.kFrontLeft, true);
//    	robotDrive.setInvertedMotor(MotorType.kRearLeft, true);
    }
    
//    double Power = 0.5;
//    double negPower = -0.5;
//    double stop = 0;
//    
//    
//    
//    public void drive(double x, double y, double rotation, double gyro)	{
//    	robotDrive.mecanumDrive_Cartesian(-x, -y, -rotation, gyro);
//    }
}

